### ISSUE TITLE
ska-registry.av.it.pt

### ISSUE THREAD

**Issue by Matteo04052017** [ska-telescope/tmc-prototype#10]
The ska-registry.av.it.pt registry is no longer working. Can you please update the dockerfile and the docker-compose file?
The new registry is this one: nexus.engageska-portugal.pt

**Comment by Matteo04052017** [comment]
I have seen there is a pending pull request from Dzianis... the sooner you approve it, the better it is...

**Comment by jyotinpo** [comment]
Done.
